

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1179, 696)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(830, 130, 191, 511))
        self.label.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/body.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_ust7 = QtWidgets.QLabel(Dialog)
        self.label_ust7.setGeometry(QtCore.QRect(840, 190, 201, 221))
        self.label_ust7.setStyleSheet("")
        self.label_ust7.setText("")
        self.label_ust7.setObjectName("label_ust7")
        self.label_ust3 = QtWidgets.QLabel(Dialog)
        self.label_ust3.setGeometry(QtCore.QRect(830, 160, 231, 221))
        self.label_ust3.setStyleSheet("")
        self.label_ust3.setText("")
        self.label_ust3.setObjectName("label_ust3")
        self.label_ust1 = QtWidgets.QLabel(Dialog)
        self.label_ust1.setGeometry(QtCore.QRect(830, 190, 221, 151))
        self.label_ust1.setStyleSheet("")
        self.label_ust1.setText("")
        self.label_ust1.setObjectName("label_ust1")
        self.label_ust2 = QtWidgets.QLabel(Dialog)
        self.label_ust2.setGeometry(QtCore.QRect(820, 150, 231, 261))
        self.label_ust2.setStyleSheet("")
        self.label_ust2.setText("")
        self.label_ust2.setObjectName("label_ust2")
        self.label_ust4 = QtWidgets.QLabel(Dialog)
        self.label_ust4.setGeometry(QtCore.QRect(860, 180, 161, 171))
        self.label_ust4.setStyleSheet("")
        self.label_ust4.setText("")
        self.label_ust4.setObjectName("label_ust4")
        self.label_ust5 = QtWidgets.QLabel(Dialog)
        self.label_ust5.setGeometry(QtCore.QRect(840, 190, 191, 221))
        self.label_ust5.setStyleSheet("")
        self.label_ust5.setText("")
        self.label_ust5.setObjectName("label_ust5")
        self.label_ust6 = QtWidgets.QLabel(Dialog)
        self.label_ust6.setGeometry(QtCore.QRect(850, 180, 181, 211))
        self.label_ust6.setStyleSheet("")
        self.label_ust6.setText("")
        self.label_ust6.setObjectName("label_ust6")
        self.label_ust8 = QtWidgets.QLabel(Dialog)
        self.label_ust8.setGeometry(QtCore.QRect(840, 190, 201, 211))
        self.label_ust8.setStyleSheet("")
        self.label_ust8.setText("")
        self.label_ust8.setObjectName("label_ust8")
        self.label_ust9 = QtWidgets.QLabel(Dialog)
        self.label_ust9.setGeometry(QtCore.QRect(850, 190, 181, 201))
        self.label_ust9.setStyleSheet("")
        self.label_ust9.setText("")
        self.label_ust9.setObjectName("label_ust9")
        self.label_ust10 = QtWidgets.QLabel(Dialog)
        self.label_ust10.setGeometry(QtCore.QRect(820, 160, 241, 271))
        self.label_ust10.setStyleSheet("")
        self.label_ust10.setText("")
        self.label_ust10.setObjectName("label_ust10")
        self.label_alt1 = QtWidgets.QLabel(Dialog)
        self.label_alt1.setGeometry(QtCore.QRect(840, 270, 171, 321))
        self.label_alt1.setStyleSheet("")
        self.label_alt1.setText("")
        self.label_alt1.setObjectName("label_alt1")
        self.label_alt2 = QtWidgets.QLabel(Dialog)
        self.label_alt2.setGeometry(QtCore.QRect(800, 270, 241, 351))
        self.label_alt2.setStyleSheet("")
        self.label_alt2.setText("")
        self.label_alt2.setObjectName("label_alt2")
        self.label_alt3 = QtWidgets.QLabel(Dialog)
        self.label_alt3.setGeometry(QtCore.QRect(830, 270, 211, 231))
        self.label_alt3.setStyleSheet("")
        self.label_alt3.setText("")
        self.label_alt3.setObjectName("label_alt3")
        self.label_alt4 = QtWidgets.QLabel(Dialog)
        self.label_alt4.setGeometry(QtCore.QRect(840, 270, 191, 271))
        self.label_alt4.setStyleSheet("")
        self.label_alt4.setText("")
        self.label_alt4.setObjectName("label_alt4")
        self.label_alt5 = QtWidgets.QLabel(Dialog)
        self.label_alt5.setGeometry(QtCore.QRect(870, 260, 131, 221))
        self.label_alt5.setStyleSheet("")
        self.label_alt5.setText("")
        self.label_alt5.setObjectName("label_alt5")
        self.label_alt6 = QtWidgets.QLabel(Dialog)
        self.label_alt6.setGeometry(QtCore.QRect(850, 260, 191, 301))
        self.label_alt6.setStyleSheet("")
        self.label_alt6.setText("")
        self.label_alt6.setObjectName("label_alt6")
        self.label_alt7 = QtWidgets.QLabel(Dialog)
        self.label_alt7.setGeometry(QtCore.QRect(860, 290, 161, 131))
        self.label_alt7.setStyleSheet("")
        self.label_alt7.setText("")
        self.label_alt7.setObjectName("label_alt7")
        self.label_alt8 = QtWidgets.QLabel(Dialog)
        self.label_alt8.setGeometry(QtCore.QRect(830, 270, 191, 291))
        self.label_alt8.setStyleSheet("")
        self.label_alt8.setText("")
        self.label_alt8.setObjectName("label_alt8")
        self.label_alt10 = QtWidgets.QLabel(Dialog)
        self.label_alt10.setGeometry(QtCore.QRect(860, 270, 151, 251))
        self.label_alt10.setStyleSheet("")
        self.label_alt10.setText("")
        self.label_alt10.setObjectName("label_alt10")
        self.label_alt9 = QtWidgets.QLabel(Dialog)
        self.label_alt9.setGeometry(QtCore.QRect(820, 280, 201, 331))
        self.label_alt9.setStyleSheet("")
        self.label_alt9.setText("")
        self.label_alt9.setObjectName("label_alt9")
        self.label_alt11 = QtWidgets.QLabel(Dialog)
        self.label_alt11.setGeometry(QtCore.QRect(860, 280, 151, 211))
        self.label_alt11.setStyleSheet("")
        self.label_alt11.setText("")
        self.label_alt11.setObjectName("label_alt11")
        self.label_sac = QtWidgets.QLabel(Dialog)
        self.label_sac.setGeometry(QtCore.QRect(830, 80, 231, 181))
        self.label_sac.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/sac2.png);")
        self.label_sac.setText("")
        self.label_sac.setObjectName("label_sac")
        self.label_elb2 = QtWidgets.QLabel(Dialog)
        self.label_elb2.setGeometry(QtCore.QRect(840, 170, 201, 301))
        self.label_elb2.setStyleSheet("")
        self.label_elb2.setText("")
        self.label_elb2.setObjectName("label_elb2")
        self.label_elb3 = QtWidgets.QLabel(Dialog)
        self.label_elb3.setGeometry(QtCore.QRect(850, 190, 181, 251))
        self.label_elb3.setStyleSheet("")
        self.label_elb3.setText("")
        self.label_elb3.setObjectName("label_elb3")
        self.label_elb4 = QtWidgets.QLabel(Dialog)
        self.label_elb4.setGeometry(QtCore.QRect(860, 190, 161, 261))
        self.label_elb4.setStyleSheet("")
        self.label_elb4.setText("")
        self.label_elb4.setObjectName("label_elb4")
        self.label_elb6 = QtWidgets.QLabel(Dialog)
        self.label_elb6.setGeometry(QtCore.QRect(830, 190, 211, 361))
        self.label_elb6.setStyleSheet("")
        self.label_elb6.setText("")
        self.label_elb6.setObjectName("label_elb6")
        self.label_elb7 = QtWidgets.QLabel(Dialog)
        self.label_elb7.setGeometry(QtCore.QRect(860, 180, 161, 321))
        self.label_elb7.setStyleSheet("")
        self.label_elb7.setText("")
        self.label_elb7.setObjectName("label_elb7")
        self.label_elb8 = QtWidgets.QLabel(Dialog)
        self.label_elb8.setGeometry(QtCore.QRect(840, 170, 191, 261))
        self.label_elb8.setStyleSheet("")
        self.label_elb8.setText("")
        self.label_elb8.setObjectName("label_elb8")
        self.label_elb9 = QtWidgets.QLabel(Dialog)
        self.label_elb9.setGeometry(QtCore.QRect(860, 190, 151, 261))
        self.label_elb9.setStyleSheet("")
        self.label_elb9.setText("")
        self.label_elb9.setObjectName("label_elb9")
        self.label_elb10 = QtWidgets.QLabel(Dialog)
        self.label_elb10.setGeometry(QtCore.QRect(830, 200, 211, 331))
        self.label_elb10.setStyleSheet("")
        self.label_elb10.setText("")
        self.label_elb10.setObjectName("label_elb10")
        self.label_elb1 = QtWidgets.QLabel(Dialog)
        self.label_elb1.setGeometry(QtCore.QRect(830, 190, 211, 341))
        self.label_elb1.setStyleSheet("")
        self.label_elb1.setText("")
        self.label_elb1.setObjectName("label_elb1")
        self.label_elb5 = QtWidgets.QLabel(Dialog)
        self.label_elb5.setGeometry(QtCore.QRect(850, 190, 181, 241))
        self.label_elb5.setStyleSheet("")
        self.label_elb5.setText("")
        self.label_elb5.setObjectName("label_elb5")
        self.label_ayb1 = QtWidgets.QLabel(Dialog)
        self.label_ayb1.setGeometry(QtCore.QRect(800, 470, 231, 221))
        self.label_ayb1.setStyleSheet("")
        self.label_ayb1.setText("")
        self.label_ayb1.setObjectName("label_ayb1")
        self.label_ayb10 = QtWidgets.QLabel(Dialog)
        self.label_ayb10.setGeometry(QtCore.QRect(830, 510, 171, 171))
        self.label_ayb10.setStyleSheet("")
        self.label_ayb10.setText("")
        self.label_ayb10.setObjectName("label_ayb10")
        self.label_ayb2 = QtWidgets.QLabel(Dialog)
        self.label_ayb2.setGeometry(QtCore.QRect(800, 530, 231, 141))
        self.label_ayb2.setStyleSheet("")
        self.label_ayb2.setText("")
        self.label_ayb2.setObjectName("label_ayb2")
        self.label_ayb3 = QtWidgets.QLabel(Dialog)
        self.label_ayb3.setGeometry(QtCore.QRect(830, 540, 171, 111))
        self.label_ayb3.setStyleSheet("")
        self.label_ayb3.setText("")
        self.label_ayb3.setObjectName("label_ayb3")
        self.label_ayb6 = QtWidgets.QLabel(Dialog)
        self.label_ayb6.setGeometry(QtCore.QRect(800, 550, 231, 101))
        self.label_ayb6.setStyleSheet("")
        self.label_ayb6.setText("")
        self.label_ayb6.setObjectName("label_ayb6")
        self.label_ayb7 = QtWidgets.QLabel(Dialog)
        self.label_ayb7.setGeometry(QtCore.QRect(790, 470, 251, 181))
        self.label_ayb7.setStyleSheet("")
        self.label_ayb7.setText("")
        self.label_ayb7.setObjectName("label_ayb7")
        self.label_ayb8 = QtWidgets.QLabel(Dialog)
        self.label_ayb8.setGeometry(QtCore.QRect(810, 400, 211, 251))
        self.label_ayb8.setStyleSheet("")
        self.label_ayb8.setText("")
        self.label_ayb8.setObjectName("label_ayb8")
        self.label_ayb9 = QtWidgets.QLabel(Dialog)
        self.label_ayb9.setGeometry(QtCore.QRect(820, 540, 181, 111))
        self.label_ayb9.setStyleSheet("")
        self.label_ayb9.setText("")
        self.label_ayb9.setObjectName("label_ayb9")
        self.label_ayb11 = QtWidgets.QLabel(Dialog)
        self.label_ayb11.setGeometry(QtCore.QRect(810, 530, 201, 131))
        self.label_ayb11.setStyleSheet("")
        self.label_ayb11.setText("")
        self.label_ayb11.setObjectName("label_ayb11")
        self.label_ayb5 = QtWidgets.QLabel(Dialog)
        self.label_ayb5.setGeometry(QtCore.QRect(820, 530, 191, 121))
        self.label_ayb5.setStyleSheet("")
        self.label_ayb5.setText("")
        self.label_ayb5.setObjectName("label_ayb5")
        self.label_ayb4 = QtWidgets.QLabel(Dialog)
        self.label_ayb4.setGeometry(QtCore.QRect(820, 520, 191, 121))
        self.label_ayb4.setStyleSheet("")
        self.label_ayb4.setText("")
        self.label_ayb4.setObjectName("label_ayb4")
        self.label_alt13 = QtWidgets.QLabel(Dialog)
        self.label_alt13.setGeometry(QtCore.QRect(760, 270, 291, 371))
        self.label_alt13.setStyleSheet("")
        self.label_alt13.setText("")
        self.label_alt13.setObjectName("label_alt13")
        self.label_alt12 = QtWidgets.QLabel(Dialog)
        self.label_alt12.setGeometry(QtCore.QRect(860, 260, 161, 161))
        self.label_alt12.setStyleSheet("")
        self.label_alt12.setText("")
        self.label_alt12.setObjectName("label_alt12")
        self.label_alt14 = QtWidgets.QLabel(Dialog)
        self.label_alt14.setGeometry(QtCore.QRect(860, 280, 161, 161))
        self.label_alt14.setStyleSheet("")
        self.label_alt14.setText("")
        self.label_alt14.setObjectName("label_alt14")
        self.label_alt15 = QtWidgets.QLabel(Dialog)
        self.label_alt15.setGeometry(QtCore.QRect(850, 260, 171, 181))
        self.label_alt15.setStyleSheet("")
        self.label_alt15.setText("")
        self.label_alt15.setObjectName("label_alt15")
        self.label_ust12 = QtWidgets.QLabel(Dialog)
        self.label_ust12.setGeometry(QtCore.QRect(830, 190, 211, 201))
        self.label_ust12.setStyleSheet("")
        self.label_ust12.setText("")
        self.label_ust12.setObjectName("label_ust12")
        self.label_ust13 = QtWidgets.QLabel(Dialog)
        self.label_ust13.setGeometry(QtCore.QRect(820, 210, 231, 191))
        self.label_ust13.setStyleSheet("")
        self.label_ust13.setText("")
        self.label_ust13.setObjectName("label_ust13")
        self.label_elb11 = QtWidgets.QLabel(Dialog)
        self.label_elb11.setGeometry(QtCore.QRect(840, 190, 201, 231))
        self.label_elb11.setStyleSheet("")
        self.label_elb11.setText("")
        self.label_elb11.setObjectName("label_elb11")
        self.label_elb12 = QtWidgets.QLabel(Dialog)
        self.label_elb12.setGeometry(QtCore.QRect(840, 170, 201, 311))
        self.label_elb12.setStyleSheet("")
        self.label_elb12.setText("")
        self.label_elb12.setObjectName("label_elb12")
        self.label_elb13 = QtWidgets.QLabel(Dialog)
        self.label_elb13.setGeometry(QtCore.QRect(840, 190, 191, 431))
        self.label_elb13.setStyleSheet("")
        self.label_elb13.setText("")
        self.label_elb13.setObjectName("label_elb13")
        self.label_elb14 = QtWidgets.QLabel(Dialog)
        self.label_elb14.setGeometry(QtCore.QRect(850, 190, 191, 421))
        self.label_elb14.setStyleSheet("")
        self.label_elb14.setText("")
        self.label_elb14.setObjectName("label_elb14")
        self.label_elb15 = QtWidgets.QLabel(Dialog)
        self.label_elb15.setGeometry(QtCore.QRect(840, 190, 211, 361))
        self.label_elb15.setStyleSheet("")
        self.label_elb15.setText("")
        self.label_elb15.setObjectName("label_elb15")
        self.label_ckt5 = QtWidgets.QLabel(Dialog)
        self.label_ckt5.setGeometry(QtCore.QRect(810, 180, 251, 411))
        self.label_ckt5.setStyleSheet("")
        self.label_ckt5.setText("")
        self.label_ckt5.setObjectName("label_ckt5")
        self.label_ckt1 = QtWidgets.QLabel(Dialog)
        self.label_ckt1.setGeometry(QtCore.QRect(830, 170, 221, 331))
        self.label_ckt1.setStyleSheet("")
        self.label_ckt1.setText("")
        self.label_ckt1.setObjectName("label_ckt1")
        self.label_ckt2 = QtWidgets.QLabel(Dialog)
        self.label_ckt2.setGeometry(QtCore.QRect(840, 190, 191, 221))
        self.label_ckt2.setStyleSheet("")
        self.label_ckt2.setText("")
        self.label_ckt2.setObjectName("label_ckt2")
        self.label_ckt3 = QtWidgets.QLabel(Dialog)
        self.label_ckt3.setGeometry(QtCore.QRect(820, 170, 231, 361))
        self.label_ckt3.setStyleSheet("")
        self.label_ckt3.setText("")
        self.label_ckt3.setObjectName("label_ckt3")
        self.label_ckt4 = QtWidgets.QLabel(Dialog)
        self.label_ckt4.setGeometry(QtCore.QRect(820, 190, 241, 211))
        self.label_ckt4.setStyleSheet("")
        self.label_ckt4.setText("")
        self.label_ckt4.setObjectName("label_ckt4")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 641, 621))
        self.tabWidget.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pb_ust9 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust9.setGeometry(QtCore.QRect(20, 290, 141, 131))
        self.pb_ust9.setStyleSheet("")
        self.pb_ust9.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust9.setIcon(icon)
        self.pb_ust9.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust9.setObjectName("pb_ust9")
        self.pb_ust6 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust6.setGeometry(QtCore.QRect(170, 150, 141, 131))
        self.pb_ust6.setStyleSheet("")
        self.pb_ust6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust6.setIcon(icon1)
        self.pb_ust6.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust6.setObjectName("pb_ust6")
        self.pb_ust5 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust5.setGeometry(QtCore.QRect(20, 150, 141, 131))
        self.pb_ust5.setStyleSheet("")
        self.pb_ust5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust5.setIcon(icon2)
        self.pb_ust5.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust5.setObjectName("pb_ust5")
        self.pb_ust7 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust7.setGeometry(QtCore.QRect(320, 150, 141, 131))
        self.pb_ust7.setStyleSheet("")
        self.pb_ust7.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust7.setIcon(icon3)
        self.pb_ust7.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust7.setObjectName("pb_ust7")
        self.pb_ust1 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust1.setGeometry(QtCore.QRect(20, 10, 141, 131))
        self.pb_ust1.setStyleSheet("")
        self.pb_ust1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1.setIcon(icon4)
        self.pb_ust1.setIconSize(QtCore.QSize(200, 200))
        self.pb_ust1.setObjectName("pb_ust1")
        self.pb_ust8 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust8.setGeometry(QtCore.QRect(470, 150, 141, 131))
        self.pb_ust8.setStyleSheet("")
        self.pb_ust8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust8.setIcon(icon5)
        self.pb_ust8.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust8.setObjectName("pb_ust8")
        self.pb_ust3 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust3.setGeometry(QtCore.QRect(320, 10, 141, 131))
        self.pb_ust3.setStyleSheet("")
        self.pb_ust3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust3.setIcon(icon6)
        self.pb_ust3.setIconSize(QtCore.QSize(200, 200))
        self.pb_ust3.setObjectName("pb_ust3")
        self.pb_ust2 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust2.setGeometry(QtCore.QRect(170, 10, 141, 131))
        self.pb_ust2.setStyleSheet("")
        self.pb_ust2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2.setIcon(icon7)
        self.pb_ust2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2.setObjectName("pb_ust2")
        self.pb_ust4 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust4.setGeometry(QtCore.QRect(470, 10, 141, 131))
        self.pb_ust4.setStyleSheet("")
        self.pb_ust4.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust4.setIcon(icon8)
        self.pb_ust4.setIconSize(QtCore.QSize(200, 200))
        self.pb_ust4.setObjectName("pb_ust4")
        self.pb_ust12 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust12.setGeometry(QtCore.QRect(20, 430, 141, 131))
        self.pb_ust12.setStyleSheet("")
        self.pb_ust12.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust12.setIcon(icon9)
        self.pb_ust12.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust12.setObjectName("pb_ust12")
        self.pb_ust11 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust11.setGeometry(QtCore.QRect(470, 290, 141, 131))
        self.pb_ust11.setStyleSheet("")
        self.pb_ust11.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust11.setIcon(icon10)
        self.pb_ust11.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust11.setObjectName("pb_ust11")
        self.pb_ust10 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust10.setGeometry(QtCore.QRect(170, 290, 141, 131))
        self.pb_ust10.setStyleSheet("")
        self.pb_ust10.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust10.setIcon(icon11)
        self.pb_ust10.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust10.setObjectName("pb_ust10")
        self.pb_ust11_2 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust11_2.setGeometry(QtCore.QRect(320, 290, 141, 131))
        self.pb_ust11_2.setStyleSheet("")
        self.pb_ust11_2.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust11_2.setIcon(icon12)
        self.pb_ust11_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust11_2.setObjectName("pb_ust11_2")
        self.pb_ust11_3 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust11_3.setGeometry(QtCore.QRect(170, 430, 141, 131))
        self.pb_ust11_3.setStyleSheet("")
        self.pb_ust11_3.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust11_3.setIcon(icon13)
        self.pb_ust11_3.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust11_3.setObjectName("pb_ust11_3")
        self.pb_ust11_4 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust11_4.setGeometry(QtCore.QRect(320, 430, 141, 131))
        self.pb_ust11_4.setStyleSheet("")
        self.pb_ust11_4.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust11_4.setIcon(icon14)
        self.pb_ust11_4.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust11_4.setObjectName("pb_ust11_4")
        self.pb_ust11_5 = QtWidgets.QPushButton(self.tab_3)
        self.pb_ust11_5.setGeometry(QtCore.QRect(470, 430, 141, 131))
        self.pb_ust11_5.setStyleSheet("")
        self.pb_ust11_5.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust11_5.setIcon(icon15)
        self.pb_ust11_5.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust11_5.setObjectName("pb_ust11_5")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pb_ust2_9 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_9.setGeometry(QtCore.QRect(170, 150, 141, 131))
        self.pb_ust2_9.setStyleSheet("")
        self.pb_ust2_9.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_9.setIcon(icon16)
        self.pb_ust2_9.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_9.setObjectName("pb_ust2_9")
        self.pb_ust2_10 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_10.setGeometry(QtCore.QRect(20, 150, 141, 131))
        self.pb_ust2_10.setStyleSheet("")
        self.pb_ust2_10.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_10.setIcon(icon17)
        self.pb_ust2_10.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2_10.setObjectName("pb_ust2_10")
        self.pb_ust2_11 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_11.setGeometry(QtCore.QRect(320, 150, 141, 131))
        self.pb_ust2_11.setStyleSheet("")
        self.pb_ust2_11.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_11.setIcon(icon18)
        self.pb_ust2_11.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2_11.setObjectName("pb_ust2_11")
        self.pb_ust2_15 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_15.setGeometry(QtCore.QRect(320, 290, 141, 131))
        self.pb_ust2_15.setStyleSheet("")
        self.pb_ust2_15.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_15.setIcon(icon19)
        self.pb_ust2_15.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2_15.setObjectName("pb_ust2_15")
        self.pb_ust1_2 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust1_2.setGeometry(QtCore.QRect(20, 10, 141, 131))
        self.pb_ust1_2.setStyleSheet("")
        self.pb_ust1_2.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_2.setIcon(icon20)
        self.pb_ust1_2.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_2.setObjectName("pb_ust1_2")
        self.pb_ust2_16 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_16.setGeometry(QtCore.QRect(470, 150, 141, 131))
        self.pb_ust2_16.setStyleSheet("")
        self.pb_ust2_16.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_16.setIcon(icon21)
        self.pb_ust2_16.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_16.setObjectName("pb_ust2_16")
        self.pb_ust2_17 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_17.setGeometry(QtCore.QRect(320, 10, 141, 131))
        self.pb_ust2_17.setStyleSheet("")
        self.pb_ust2_17.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_17.setIcon(icon22)
        self.pb_ust2_17.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust2_17.setObjectName("pb_ust2_17")
        self.pb_ust2_18 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_18.setGeometry(QtCore.QRect(470, 290, 141, 131))
        self.pb_ust2_18.setStyleSheet("")
        self.pb_ust2_18.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_18.setIcon(icon23)
        self.pb_ust2_18.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2_18.setObjectName("pb_ust2_18")
        self.pb_ust2_19 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_19.setGeometry(QtCore.QRect(170, 10, 141, 131))
        self.pb_ust2_19.setStyleSheet("")
        self.pb_ust2_19.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_19.setIcon(icon24)
        self.pb_ust2_19.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_19.setObjectName("pb_ust2_19")
        self.pb_ust2_20 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_20.setGeometry(QtCore.QRect(170, 290, 141, 131))
        self.pb_ust2_20.setStyleSheet("")
        self.pb_ust2_20.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_20.setIcon(icon25)
        self.pb_ust2_20.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_20.setObjectName("pb_ust2_20")
        self.pb_ust2_21 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_21.setGeometry(QtCore.QRect(470, 10, 141, 131))
        self.pb_ust2_21.setStyleSheet("")
        self.pb_ust2_21.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_21.setIcon(icon26)
        self.pb_ust2_21.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_21.setObjectName("pb_ust2_21")
        self.pb_ust2_22 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_22.setGeometry(QtCore.QRect(20, 290, 141, 131))
        self.pb_ust2_22.setStyleSheet("")
        self.pb_ust2_22.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_22.setIcon(icon27)
        self.pb_ust2_22.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_22.setObjectName("pb_ust2_22")
        self.pb_ust2_25 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_25.setGeometry(QtCore.QRect(20, 430, 141, 131))
        self.pb_ust2_25.setStyleSheet("")
        self.pb_ust2_25.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_25.setIcon(icon28)
        self.pb_ust2_25.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust2_25.setObjectName("pb_ust2_25")
        self.pb_ust2_23 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_23.setGeometry(QtCore.QRect(170, 430, 141, 131))
        self.pb_ust2_23.setStyleSheet("")
        self.pb_ust2_23.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_23.setIcon(icon29)
        self.pb_ust2_23.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_23.setObjectName("pb_ust2_23")
        self.pb_ust2_24 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_24.setGeometry(QtCore.QRect(320, 430, 141, 131))
        self.pb_ust2_24.setStyleSheet("")
        self.pb_ust2_24.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_24.setIcon(icon30)
        self.pb_ust2_24.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2_24.setObjectName("pb_ust2_24")
        self.pb_ust2_26 = QtWidgets.QPushButton(self.tab_4)
        self.pb_ust2_26.setGeometry(QtCore.QRect(470, 430, 141, 131))
        self.pb_ust2_26.setStyleSheet("")
        self.pb_ust2_26.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_26.setIcon(icon31)
        self.pb_ust2_26.setIconSize(QtCore.QSize(130, 130))
        self.pb_ust2_26.setObjectName("pb_ust2_26")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pb_ust1_3 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_3.setGeometry(QtCore.QRect(20, 10, 141, 131))
        self.pb_ust1_3.setStyleSheet("")
        self.pb_ust1_3.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_3.setIcon(icon32)
        self.pb_ust1_3.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_3.setObjectName("pb_ust1_3")
        self.pb_ust1_4 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_4.setGeometry(QtCore.QRect(170, 10, 141, 131))
        self.pb_ust1_4.setStyleSheet("")
        self.pb_ust1_4.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_4.setIcon(icon33)
        self.pb_ust1_4.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_4.setObjectName("pb_ust1_4")
        self.pb_ust1_5 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_5.setGeometry(QtCore.QRect(320, 10, 141, 131))
        self.pb_ust1_5.setStyleSheet("")
        self.pb_ust1_5.setText("")
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_5.setIcon(icon34)
        self.pb_ust1_5.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_5.setObjectName("pb_ust1_5")
        self.pb_ust1_6 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_6.setGeometry(QtCore.QRect(470, 10, 141, 131))
        self.pb_ust1_6.setStyleSheet("")
        self.pb_ust1_6.setText("")
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_6.setIcon(icon35)
        self.pb_ust1_6.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_6.setObjectName("pb_ust1_6")
        self.pb_ust1_7 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_7.setGeometry(QtCore.QRect(20, 150, 141, 131))
        self.pb_ust1_7.setStyleSheet("")
        self.pb_ust1_7.setText("")
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_7.setIcon(icon36)
        self.pb_ust1_7.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_7.setObjectName("pb_ust1_7")
        self.pb_ust1_8 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_8.setGeometry(QtCore.QRect(170, 150, 141, 131))
        self.pb_ust1_8.setStyleSheet("")
        self.pb_ust1_8.setText("")
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_8.setIcon(icon37)
        self.pb_ust1_8.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_8.setObjectName("pb_ust1_8")
        self.pb_ust1_9 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_9.setGeometry(QtCore.QRect(320, 150, 141, 131))
        self.pb_ust1_9.setStyleSheet("")
        self.pb_ust1_9.setText("")
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_9.setIcon(icon38)
        self.pb_ust1_9.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_9.setObjectName("pb_ust1_9")
        self.pb_ust1_10 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_10.setGeometry(QtCore.QRect(470, 150, 141, 131))
        self.pb_ust1_10.setStyleSheet("")
        self.pb_ust1_10.setText("")
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_10.setIcon(icon39)
        self.pb_ust1_10.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_10.setObjectName("pb_ust1_10")
        self.pb_ust1_11 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_11.setGeometry(QtCore.QRect(320, 430, 141, 131))
        self.pb_ust1_11.setStyleSheet("")
        self.pb_ust1_11.setText("")
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_11.setIcon(icon40)
        self.pb_ust1_11.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_11.setObjectName("pb_ust1_11")
        self.pb_ust1_12 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_12.setGeometry(QtCore.QRect(470, 290, 141, 131))
        self.pb_ust1_12.setStyleSheet("")
        self.pb_ust1_12.setText("")
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_12.setIcon(icon41)
        self.pb_ust1_12.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_12.setObjectName("pb_ust1_12")
        self.pb_ust1_13 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_13.setGeometry(QtCore.QRect(20, 430, 141, 131))
        self.pb_ust1_13.setStyleSheet("")
        self.pb_ust1_13.setText("")
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_13.setIcon(icon42)
        self.pb_ust1_13.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_13.setObjectName("pb_ust1_13")
        self.pb_ust1_14 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_14.setGeometry(QtCore.QRect(170, 430, 141, 131))
        self.pb_ust1_14.setStyleSheet("")
        self.pb_ust1_14.setText("")
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_14.setIcon(icon43)
        self.pb_ust1_14.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_14.setObjectName("pb_ust1_14")
        self.pb_ust1_15 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_15.setGeometry(QtCore.QRect(320, 290, 141, 131))
        self.pb_ust1_15.setStyleSheet("")
        self.pb_ust1_15.setText("")
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_15.setIcon(icon44)
        self.pb_ust1_15.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_15.setObjectName("pb_ust1_15")
        self.pb_ust1_16 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_16.setGeometry(QtCore.QRect(20, 290, 141, 131))
        self.pb_ust1_16.setStyleSheet("")
        self.pb_ust1_16.setText("")
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_16.setIcon(icon45)
        self.pb_ust1_16.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_16.setObjectName("pb_ust1_16")
        self.pb_ust1_17 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_17.setGeometry(QtCore.QRect(470, 430, 141, 131))
        self.pb_ust1_17.setStyleSheet("")
        self.pb_ust1_17.setText("")
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_17.setIcon(icon46)
        self.pb_ust1_17.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_17.setObjectName("pb_ust1_17")
        self.pb_ust1_18 = QtWidgets.QPushButton(self.tab_5)
        self.pb_ust1_18.setGeometry(QtCore.QRect(170, 290, 141, 131))
        self.pb_ust1_18.setStyleSheet("")
        self.pb_ust1_18.setText("")
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_18.setIcon(icon47)
        self.pb_ust1_18.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_18.setObjectName("pb_ust1_18")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(630, 540, 81, 81))
        self.pushButton_7.setText("")
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/clean_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon48)
        self.pushButton_7.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pb_ust1_19 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_19.setGeometry(QtCore.QRect(470, 10, 141, 131))
        self.pb_ust1_19.setStyleSheet("")
        self.pb_ust1_19.setText("")
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_19.setIcon(icon49)
        self.pb_ust1_19.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_19.setObjectName("pb_ust1_19")
        self.pb_ust1_21 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_21.setGeometry(QtCore.QRect(20, 150, 141, 131))
        self.pb_ust1_21.setStyleSheet("")
        self.pb_ust1_21.setText("")
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_21.setIcon(icon50)
        self.pb_ust1_21.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_21.setObjectName("pb_ust1_21")
        self.pb_ust1_22 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_22.setGeometry(QtCore.QRect(320, 10, 141, 131))
        self.pb_ust1_22.setStyleSheet("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt3.png);")
        self.pb_ust1_22.setText("")
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_22.setIcon(icon51)
        self.pb_ust1_22.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_22.setObjectName("pb_ust1_22")
        self.pb_ust1_24 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_24.setGeometry(QtCore.QRect(20, 10, 141, 131))
        self.pb_ust1_24.setStyleSheet("")
        self.pb_ust1_24.setText("")
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_24.setIcon(icon52)
        self.pb_ust1_24.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_24.setObjectName("pb_ust1_24")
        self.pb_ust1_26 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_26.setGeometry(QtCore.QRect(170, 10, 141, 131))
        self.pb_ust1_26.setStyleSheet("")
        self.pb_ust1_26.setText("")
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_26.setIcon(icon53)
        self.pb_ust1_26.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_26.setObjectName("pb_ust1_26")
        self.pb_ust1_23 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_23.setGeometry(QtCore.QRect(170, 150, 141, 131))
        self.pb_ust1_23.setStyleSheet("")
        self.pb_ust1_23.setText("")
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_23.setIcon(icon54)
        self.pb_ust1_23.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_23.setObjectName("pb_ust1_23")
        self.pb_ust1_25 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_25.setGeometry(QtCore.QRect(320, 150, 141, 131))
        self.pb_ust1_25.setStyleSheet("")
        self.pb_ust1_25.setText("")
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_25.setIcon(icon55)
        self.pb_ust1_25.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_25.setObjectName("pb_ust1_25")
        self.pb_ust1_27 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_27.setGeometry(QtCore.QRect(470, 150, 141, 131))
        self.pb_ust1_27.setStyleSheet("")
        self.pb_ust1_27.setText("")
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_27.setIcon(icon56)
        self.pb_ust1_27.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_27.setObjectName("pb_ust1_27")
        self.pb_ust1_28 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_28.setGeometry(QtCore.QRect(20, 290, 141, 131))
        self.pb_ust1_28.setStyleSheet("")
        self.pb_ust1_28.setText("")
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_28.setIcon(icon57)
        self.pb_ust1_28.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_28.setObjectName("pb_ust1_28")
        self.pb_ust1_29 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_29.setGeometry(QtCore.QRect(170, 290, 141, 131))
        self.pb_ust1_29.setStyleSheet("")
        self.pb_ust1_29.setText("")
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_29.setIcon(icon58)
        self.pb_ust1_29.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_29.setObjectName("pb_ust1_29")
        self.pb_ust1_30 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_30.setGeometry(QtCore.QRect(320, 290, 141, 131))
        self.pb_ust1_30.setStyleSheet("")
        self.pb_ust1_30.setText("")
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_30.setIcon(icon59)
        self.pb_ust1_30.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_30.setObjectName("pb_ust1_30")
        self.pb_ust1_31 = QtWidgets.QPushButton(self.tab_6)
        self.pb_ust1_31.setGeometry(QtCore.QRect(470, 290, 141, 131))
        self.pb_ust1_31.setStyleSheet("")
        self.pb_ust1_31.setText("")
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/empty.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_31.setIcon(icon60)
        self.pb_ust1_31.setIconSize(QtCore.QSize(120, 120))
        self.pb_ust1_31.setObjectName("pb_ust1_31")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pb_ust6_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust6_2.setGeometry(QtCore.QRect(170, 150, 141, 131))
        self.pb_ust6_2.setStyleSheet("")
        self.pb_ust6_2.setText("")
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust6_2.setIcon(icon61)
        self.pb_ust6_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust6_2.setObjectName("pb_ust6_2")
        self.pb_ust5_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust5_2.setGeometry(QtCore.QRect(20, 150, 141, 131))
        self.pb_ust5_2.setStyleSheet("")
        self.pb_ust5_2.setText("")
        icon62 = QtGui.QIcon()
        icon62.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust5_2.setIcon(icon62)
        self.pb_ust5_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust5_2.setObjectName("pb_ust5_2")
        self.pb_ust7_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust7_2.setGeometry(QtCore.QRect(320, 150, 141, 131))
        self.pb_ust7_2.setStyleSheet("")
        self.pb_ust7_2.setText("")
        icon63 = QtGui.QIcon()
        icon63.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust7_2.setIcon(icon63)
        self.pb_ust7_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust7_2.setObjectName("pb_ust7_2")
        self.pb_ust1_20 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust1_20.setGeometry(QtCore.QRect(20, 10, 141, 131))
        self.pb_ust1_20.setStyleSheet("")
        self.pb_ust1_20.setText("")
        icon64 = QtGui.QIcon()
        icon64.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust1_20.setIcon(icon64)
        self.pb_ust1_20.setIconSize(QtCore.QSize(200, 200))
        self.pb_ust1_20.setObjectName("pb_ust1_20")
        self.pb_ust8_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust8_2.setGeometry(QtCore.QRect(470, 150, 141, 131))
        self.pb_ust8_2.setStyleSheet("")
        self.pb_ust8_2.setText("")
        icon65 = QtGui.QIcon()
        icon65.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust8_2.setIcon(icon65)
        self.pb_ust8_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust8_2.setObjectName("pb_ust8_2")
        self.pb_ust3_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust3_2.setGeometry(QtCore.QRect(320, 10, 141, 131))
        self.pb_ust3_2.setStyleSheet("")
        self.pb_ust3_2.setText("")
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust3_2.setIcon(icon66)
        self.pb_ust3_2.setIconSize(QtCore.QSize(200, 200))
        self.pb_ust3_2.setObjectName("pb_ust3_2")
        self.pb_ust11_8 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust11_8.setGeometry(QtCore.QRect(320, 290, 141, 131))
        self.pb_ust11_8.setStyleSheet("")
        self.pb_ust11_8.setText("")
        icon67 = QtGui.QIcon()
        icon67.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust11_8.setIcon(icon67)
        self.pb_ust11_8.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust11_8.setObjectName("pb_ust11_8")
        self.pb_ust2_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust2_2.setGeometry(QtCore.QRect(170, 10, 141, 131))
        self.pb_ust2_2.setStyleSheet("")
        self.pb_ust2_2.setText("")
        icon68 = QtGui.QIcon()
        icon68.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust2_2.setIcon(icon68)
        self.pb_ust2_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust2_2.setObjectName("pb_ust2_2")
        self.pb_ust10_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust10_2.setGeometry(QtCore.QRect(170, 290, 141, 131))
        self.pb_ust10_2.setStyleSheet("")
        self.pb_ust10_2.setText("")
        icon69 = QtGui.QIcon()
        icon69.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust10_2.setIcon(icon69)
        self.pb_ust10_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust10_2.setObjectName("pb_ust10_2")
        self.pb_ust4_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust4_2.setGeometry(QtCore.QRect(470, 10, 141, 131))
        self.pb_ust4_2.setStyleSheet("")
        self.pb_ust4_2.setText("")
        icon70 = QtGui.QIcon()
        icon70.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust4_2.setIcon(icon70)
        self.pb_ust4_2.setIconSize(QtCore.QSize(200, 200))
        self.pb_ust4_2.setObjectName("pb_ust4_2")
        self.pb_ust9_2 = QtWidgets.QPushButton(self.tab_7)
        self.pb_ust9_2.setGeometry(QtCore.QRect(20, 290, 141, 131))
        self.pb_ust9_2.setStyleSheet("")
        self.pb_ust9_2.setText("")
        icon71 = QtGui.QIcon()
        icon71.addPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_ust9_2.setIcon(icon71)
        self.pb_ust9_2.setIconSize(QtCore.QSize(140, 140))
        self.pb_ust9_2.setObjectName("pb_ust9_2")
        self.tabWidget.addTab(self.tab_7, "")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(640, 50, 81, 81))
        self.pushButton.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.pushButton.setText("")
        self.pushButton.setIcon(icon11)
        self.pushButton.setIconSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 150, 81, 81))
        self.pushButton_2.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon27)
        self.pushButton_2.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 250, 81, 81))
        self.pushButton_3.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon41)
        self.pushButton_3.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 350, 81, 81))
        self.pushButton_4.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon58)
        self.pushButton_4.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(640, 450, 81, 81))
        self.pushButton_5.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon64)
        self.pushButton_5.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_ust11 = QtWidgets.QLabel(Dialog)
        self.label_ust11.setGeometry(QtCore.QRect(830, 180, 211, 231))
        self.label_ust11.setStyleSheet("")
        self.label_ust11.setText("")
        self.label_ust11.setObjectName("label_ust11")
        self.label_ust14 = QtWidgets.QLabel(Dialog)
        self.label_ust14.setGeometry(QtCore.QRect(860, 180, 161, 231))
        self.label_ust14.setStyleSheet("")
        self.label_ust14.setText("")
        self.label_ust14.setObjectName("label_ust14")
        self.label_ust15 = QtWidgets.QLabel(Dialog)
        self.label_ust15.setGeometry(QtCore.QRect(860, 180, 161, 141))
        self.label_ust15.setStyleSheet("")
        self.label_ust15.setText("")
        self.label_ust15.setObjectName("label_ust15")
        self.label_elb16 = QtWidgets.QLabel(Dialog)
        self.label_elb16.setGeometry(QtCore.QRect(820, 190, 251, 341))
        self.label_elb16.setStyleSheet("")
        self.label_elb16.setText("")
        self.label_elb16.setObjectName("label_elb16")
        self.label_ckt6 = QtWidgets.QLabel(Dialog)
        self.label_ckt6.setGeometry(QtCore.QRect(840, 180, 201, 401))
        self.label_ckt6.setStyleSheet("")
        self.label_ckt6.setText("")
        self.label_ckt6.setObjectName("label_ckt6")
        self.label_ckt7 = QtWidgets.QLabel(Dialog)
        self.label_ckt7.setGeometry(QtCore.QRect(840, 170, 201, 251))
        self.label_ckt7.setStyleSheet("")
        self.label_ckt7.setText("")
        self.label_ckt7.setObjectName("label_ckt7")
        self.label_ckt8 = QtWidgets.QLabel(Dialog)
        self.label_ckt8.setGeometry(QtCore.QRect(840, 190, 201, 211))
        self.label_ckt8.setStyleSheet("")
        self.label_ckt8.setText("")
        self.label_ckt8.setObjectName("label_ckt8")
        self.label_ckt9 = QtWidgets.QLabel(Dialog)
        self.label_ckt9.setGeometry(QtCore.QRect(830, 160, 211, 241))
        self.label_ckt9.setStyleSheet("")
        self.label_ckt9.setText("")
        self.label_ckt9.setObjectName("label_ckt9")
        self.label_ckt10 = QtWidgets.QLabel(Dialog)
        self.label_ckt10.setGeometry(QtCore.QRect(840, 180, 201, 251))
        self.label_ckt10.setStyleSheet("")
        self.label_ckt10.setText("")
        self.label_ckt10.setObjectName("label_ckt10")
        self.label_ckt11 = QtWidgets.QLabel(Dialog)
        self.label_ckt11.setGeometry(QtCore.QRect(820, 180, 231, 251))
        self.label_ckt11.setStyleSheet("")
        self.label_ckt11.setText("")
        self.label_ckt11.setObjectName("label_ckt11")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 1181, 701))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/bg2.png);")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setLineWidth(1)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/pc/PycharmProjects/DressUpGame/img/bg5.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(640, 550, 81, 71))
        self.pushButton_6.setStyleSheet("background-color: rgb(244, 203, 255);")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon48)
        self.pushButton_6.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_alt16 = QtWidgets.QLabel(Dialog)
        self.label_alt16.setGeometry(QtCore.QRect(850, 260, 181, 201))
        self.label_alt16.setStyleSheet("")
        self.label_alt16.setText("")
        self.label_alt16.setObjectName("label_alt16")
        self.label_ust16 = QtWidgets.QLabel(Dialog)
        self.label_ust16.setGeometry(QtCore.QRect(830, 170, 221, 161))
        self.label_ust16.setStyleSheet("")
        self.label_ust16.setText("")
        self.label_ust16.setObjectName("label_ust16")

        self.label_2.raise_()
        self.label.raise_()
        self.label_sac.raise_()

        self.label_ayb1.raise_()
        self.label_ayb10.raise_()
        self.label_ayb2.raise_()
        self.label_ayb3.raise_()
        self.label_ayb6.raise_()
        self.label_ayb7.raise_()
        self.label_ayb8.raise_()
        self.label_ayb9.raise_()
        self.label_ayb11.raise_()
        self.label_ayb5.raise_()
        self.label_ayb4.raise_()

        self.label_alt1.raise_()
        self.label_alt2.raise_()
        self.label_alt3.raise_()
        self.label_alt4.raise_()
        self.label_alt5.raise_()
        self.label_alt6.raise_()
        self.label_alt7.raise_()
        self.label_alt8.raise_()
        self.label_alt10.raise_()
        self.label_alt9.raise_()
        self.label_alt11.raise_()
        self.label_alt13.raise_()
        self.label_alt12.raise_()
        self.label_alt14.raise_()
        self.label_alt15.raise_()
        self.label_alt16.raise_()

        self.label_ust7.raise_()
        self.label_ust3.raise_()
        self.label_ust1.raise_()
        self.label_ust2.raise_()
        self.label_ust4.raise_()
        self.label_ust5.raise_()
        self.label_ust6.raise_()
        self.label_ust8.raise_()
        self.label_ust9.raise_()
        self.label_ust10.raise_()
        self.label_ust12.raise_()
        self.label_ust13.raise_()
        self.label_ust16.raise_()
        self.label_ust11.raise_()
        self.label_ust14.raise_()
        self.label_ust15.raise_()

        self.label_elb2.raise_()
        self.label_elb3.raise_()
        self.label_elb4.raise_()
        self.label_elb6.raise_()
        self.label_elb7.raise_()
        self.label_elb8.raise_()
        self.label_elb9.raise_()
        self.label_elb10.raise_()
        self.label_elb1.raise_()
        self.label_elb5.raise_()
        self.label_elb16.raise_()
        self.label_elb11.raise_()
        self.label_elb12.raise_()
        self.label_elb13.raise_()
        self.label_elb14.raise_()
        self.label_elb15.raise_()

        self.label_ckt5.raise_()
        self.label_ckt1.raise_()
        self.label_ckt2.raise_()
        self.label_ckt3.raise_()
        self.label_ckt4.raise_()
        self.label_ckt6.raise_()
        self.label_ckt7.raise_()
        self.label_ckt8.raise_()
        self.label_ckt9.raise_()
        self.label_ckt10.raise_()
        self.label_ckt11.raise_()

        self.tabWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.Handle_UI_Changes()
        self.Handle_Buttons()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Page"))

    def Handle_UI_Changes(self):
        self.tabWidget.tabBar().setVisible(False)
        Dialog.setWindowTitle("DressUpGame")
        Dialog.setWindowIcon(QtGui.QIcon("C:/Users/pc/PycharmProjects/DressUpGame/img/logo.png"))

### HANDLE BUTTONS ##


    def Handle_Buttons(self):
        #opening
        self.pushButton.clicked.connect(self.alt)
        self.pushButton_2.clicked.connect(self.ust)
        self.pushButton_3.clicked.connect(self.elb)
        self.pushButton_4.clicked.connect(self.ckt)
        self.pushButton_5.clicked.connect(self.ayb)

        #dressing elb
        self.pb_ust1_3.clicked.connect(self.elb1)
        self.pb_ust1_4.clicked.connect(self.elb2)
        self.pb_ust1_5.clicked.connect(self.elb3)
        self.pb_ust1_6.clicked.connect(self.elb4)
        self.pb_ust1_7.clicked.connect(self.elb5)
        self.pb_ust1_8.clicked.connect(self.elb6)
        self.pb_ust1_9.clicked.connect(self.elb7)
        self.pb_ust1_10.clicked.connect(self.elb8)
        self.pb_ust1_16.clicked.connect(self.elb9)
        self.pb_ust1_18.clicked.connect(self.elb10)
        self.pb_ust1_15.clicked.connect(self.elb11)
        self.pb_ust1_12.clicked.connect(self.elb12)
        self.pb_ust1_13.clicked.connect(self.elb13)
        self.pb_ust1_14.clicked.connect(self.elb14)
        self.pb_ust1_11.clicked.connect(self.elb15)
        self.pb_ust1_17.clicked.connect(self.elb16)

        #dressing ust
        self.pb_ust1.clicked.connect(self.ust1)
        self.pb_ust2.clicked.connect(self.ust2)
        self.pb_ust3.clicked.connect(self.ust3)
        self.pb_ust4.clicked.connect(self.ust4)
        self.pb_ust5.clicked.connect(self.ust5)
        self.pb_ust6.clicked.connect(self.ust6)
        self.pb_ust7.clicked.connect(self.ust7)
        self.pb_ust8.clicked.connect(self.ust8)
        self.pb_ust9.clicked.connect(self.ust9)
        self.pb_ust10.clicked.connect(self.ust10)
        self.pb_ust11_2.clicked.connect(self.ust11)
        self.pb_ust11.clicked.connect(self.ust12)
        self.pb_ust12.clicked.connect(self.ust13)
        self.pb_ust11_3.clicked.connect(self.ust14)
        self.pb_ust11_4.clicked.connect(self.ust15)
        self.pb_ust11_5.clicked.connect(self.ust16)

        #dressing alt
        self.pb_ust1_2.clicked.connect(self.alt1)
        self.pb_ust2_19.clicked.connect(self.alt2)
        self.pb_ust2_17.clicked.connect(self.alt3)
        self.pb_ust2_21.clicked.connect(self.alt4)
        self.pb_ust2_10.clicked.connect(self.alt5)
        self.pb_ust2_9.clicked.connect(self.alt6)
        self.pb_ust2_11.clicked.connect(self.alt7)
        self.pb_ust2_16.clicked.connect(self.alt8)
        self.pb_ust2_22.clicked.connect(self.alt9)
        self.pb_ust2_20.clicked.connect(self.alt10)
        self.pb_ust2_15.clicked.connect(self.alt11)
        self.pb_ust2_18.clicked.connect(self.alt12)
        self.pb_ust2_25.clicked.connect(self.alt13)
        self.pb_ust2_23.clicked.connect(self.alt14)
        self.pb_ust2_24.clicked.connect(self.alt15)
        self.pb_ust2_26.clicked.connect(self.alt16)

        #dressing ckt
        self.pb_ust1_24.clicked.connect(self.ckt1)
        self.pb_ust1_26.clicked.connect(self.ckt2)
        self.pb_ust1_22.clicked.connect(self.ckt3)
        self.pb_ust1_19.clicked.connect(self.ckt4)
        self.pb_ust1_21.clicked.connect(self.ckt5)
        self.pb_ust1_23.clicked.connect(self.ckt6)
        self.pb_ust1_25.clicked.connect(self.ckt7)
        self.pb_ust1_27.clicked.connect(self.ckt8)
        self.pb_ust1_28.clicked.connect(self.ckt9)
        self.pb_ust1_29.clicked.connect(self.ckt10)
        self.pb_ust1_30.clicked.connect(self.ckt11)
        self.pb_ust1_31.clicked.connect(self.ckt_yok)

        #dressing ayakkabı
        self.pb_ust1_20.clicked.connect(self.ayb1)
        self.pb_ust2_2.clicked.connect(self.ayb2)
        self.pb_ust3_2.clicked.connect(self.ayb3)
        self.pb_ust4_2.clicked.connect(self.ayb4)
        self.pb_ust5_2.clicked.connect(self.ayb5)
        self.pb_ust6_2.clicked.connect(self.ayb6)
        self.pb_ust7_2.clicked.connect(self.ayb7)
        self.pb_ust8_2.clicked.connect(self.ayb8)
        self.pb_ust9_2.clicked.connect(self.ayb9)
        self.pb_ust10_2.clicked.connect(self.ayb10)
        self.pb_ust11_8.clicked.connect(self.ayb11)

        ## clean all
        self.pushButton_6.clicked.connect(self.clean_all)

    ### OPENING ##

    def alt(self): self.tabWidget.setCurrentIndex(0)
    def ust(self): self.tabWidget.setCurrentIndex(1)
    def elb(self): self.tabWidget.setCurrentIndex(2)
    def ayb(self): self.tabWidget.setCurrentIndex(4)
    def ckt(self): self.tabWidget.setCurrentIndex(3)

### DRESSING elb
    def bos_elb(self):
        self.label_elb1.setStyleSheet("")
        self.label_elb2.setStyleSheet("")
        self.label_elb3.setStyleSheet("")
        self.label_elb4.setStyleSheet("")
        self.label_elb5.setStyleSheet("")
        self.label_elb6.setStyleSheet("")
        self.label_elb7.setStyleSheet("")
        self.label_elb8.setStyleSheet("")
        self.label_elb9.setStyleSheet("")
        self.label_elb10.setStyleSheet("")
        self.label_elb11.setStyleSheet("")
        self.label_elb12.setStyleSheet("")
        self.label_elb13.setStyleSheet("")
        self.label_elb14.setStyleSheet("")
        self.label_elb15.setStyleSheet("")
        self.label_elb16.setStyleSheet("")
    def elb1(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb1.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb1.png);")

    def elb2(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb2.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb2.png);")

    def elb3(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb3.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb3.png);")

    def elb4(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb4.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb4.png);")

    def elb5(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb5.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb5.png);")

    def elb6(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb6.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb6.png);")

    def elb7(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb7.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb7.png);")

    def elb8(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb8.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb8.png);")

    def elb9(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb9.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb9.png);")

    def elb10(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb10.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb10.png);")

    def elb11(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb11.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb11.png);")

    def elb12(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb12.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb12.png);")

    def elb13(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb13.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb13.png);")

    def elb14(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb14.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb14.png);")

    def elb15(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb15.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb15.png);")
    def elb16(self):
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()
        self.label_elb16.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/elb/elb16.png);")
    #dressing ust

    def bos_ust(self):
        self.label_ust1.setStyleSheet("")
        self.label_ust2.setStyleSheet("")
        self.label_ust3.setStyleSheet("")
        self.label_ust4.setStyleSheet("")
        self.label_ust5.setStyleSheet("")
        self.label_ust6.setStyleSheet("")
        self.label_ust7.setStyleSheet("")
        self.label_ust8.setStyleSheet("")
        self.label_ust9.setStyleSheet("")
        self.label_ust10.setStyleSheet("")
        self.label_ust11.setStyleSheet("")
        self.label_ust12.setStyleSheet("")
        self.label_ust13.setStyleSheet("")
        self.label_ust14.setStyleSheet("")
        self.label_ust15.setStyleSheet("")
        self.label_ust16.setStyleSheet("")
    def ust1(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust1.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_1.png);")

    def ust2(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust2.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_2.png);")

    def ust3(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust3.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_3.png);")

    def ust4(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust4.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_4.png);")

    def ust5(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust5.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_5.png);")

    def ust6(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust6.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_6.png);")

    def ust7(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust7.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_7.png);")

    def ust8(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust8.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_8.png);")

    def ust9(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust9.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_9.png);")

    def ust10(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust10.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust_10.png);")

    def ust11(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust11.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust11.png);")

    def ust12(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust12.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust12.png);")

    def ust13(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust13.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust13.png);")

    def ust14(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust14.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust14.png);")

    def ust15(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust15.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust15.png);")

    def ust16(self):
        self.bos_elb()
        self.bos_ust()
        self.label_ust16.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ust/ust16.png);")

    ##dressing alt
    def bos_alt(self):
        self.label_alt1.setStyleSheet("")
        self.label_alt2.setStyleSheet("")
        self.label_alt3.setStyleSheet("")
        self.label_alt4.setStyleSheet("")
        self.label_alt5.setStyleSheet("")
        self.label_alt6.setStyleSheet("")
        self.label_alt7.setStyleSheet("")
        self.label_alt8.setStyleSheet("")
        self.label_alt9.setStyleSheet("")
        self.label_alt10.setStyleSheet("")
        self.label_alt11.setStyleSheet("")
        self.label_alt12.setStyleSheet("")
        self.label_alt13.setStyleSheet("")
        self.label_alt14.setStyleSheet("")
        self.label_alt15.setStyleSheet("")
        self.label_alt16.setStyleSheet("")

    def alt1(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt1.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt1.png);")

    def alt2(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt2.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt2.png);")

    def alt3(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt3.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt3.png);")

    def alt4(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt4.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt4.png);")

    def alt5(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt5.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt5.png);")

    def alt6(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt6.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt6.png);")

    def alt7(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt7.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt7.png);")

    def alt8(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt8.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt8.png);")

    def alt9(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt9.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt9.png);")

    def alt10(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt10.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt10.png);")

    def alt11(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt11.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt11.png);")

    def alt12(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt12.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt12.png);")

    def alt13(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt13.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt13.png);")

    def alt14(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt14.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt14.png);")

    def alt15(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt15.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt15.png);")

    def alt16(self):
        self.bos_elb()
        self.bos_alt()
        self.label_alt16.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/alt/alt16.png);")

    #dressing ceket
    def bos_ckt(self):
        self.label_ckt1.setStyleSheet("")
        self.label_ckt2.setStyleSheet("")
        self.label_ckt3.setStyleSheet("")
        self.label_ckt4.setStyleSheet("")
        self.label_ckt5.setStyleSheet("")
        self.label_ckt6.setStyleSheet("")
        self.label_ckt7.setStyleSheet("")
        self.label_ckt8.setStyleSheet("")
        self.label_ckt9.setStyleSheet("")
        self.label_ckt10.setStyleSheet("")
        self.label_ckt11.setStyleSheet("")

    def ckt1(self):
        self.bos_ckt()
        self.label_ckt1.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt1.png);")

    def ckt2(self):
        self.bos_ckt()
        self.label_ckt2.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt2.png);")

    def ckt3(self):
        self.bos_ckt()
        self.label_ckt3.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt3.png);")

    def ckt4(self):
        self.bos_ckt()
        self.label_ckt4.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt4.png);")

    def ckt5(self):
        self.bos_ckt()
        self.label_ckt5.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt5.png);")

    def ckt6(self):
        self.bos_ckt()
        self.label_ckt6.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt6.png);")

    def ckt7(self):
        self.bos_ckt()
        self.label_ckt7.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt7.png);")

    def ckt8(self):
        self.bos_ckt()
        self.label_ckt8.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt8.png);")

    def ckt9(self):
        self.bos_ckt()
        self.label_ckt9.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt9.png);")

    def ckt10(self):
        self.bos_ckt()
        self.label_ckt10.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt10.png);")

    def ckt11(self):
        self.bos_ckt()
        self.label_ckt11.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ckt/ckt11.png);")

    def ckt_yok(self):
        self.bos_ckt()

    def clean_all(self):
        self.bos_ckt()
        self.bos_ayb()
        self.bos_alt()
        self.bos_ust()
        self.bos_elb()

    ##dress ayakkabı

    def bos_ayb(self):
        self.label_ayb1.setStyleSheet("")
        self.label_ayb2.setStyleSheet("")
        self.label_ayb3.setStyleSheet("")
        self.label_ayb4.setStyleSheet("")
        self.label_ayb5.setStyleSheet("")
        self.label_ayb6.setStyleSheet("")
        self.label_ayb7.setStyleSheet("")
        self.label_ayb8.setStyleSheet("")
        self.label_ayb9.setStyleSheet("")
        self.label_ayb10.setStyleSheet("")
        self.label_ayb11.setStyleSheet("")

    def ayb1(self):
        self.bos_ayb()
        self.label_ayb1.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb1.png);")
    def ayb2(self):
        self.bos_ayb()
        self.label_ayb2.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb2.png);")
    def ayb3(self):
        self.bos_ayb()
        self.label_ayb3.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb3.png);")
    def ayb4(self):
        self.bos_ayb()
        self.label_ayb4.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb4.png);")
    def ayb5(self):
        self.bos_ayb()
        self.label_ayb5.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb5.png);")
    def ayb6(self):
        self.bos_ayb()
        self.label_ayb6.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb6.png);")
    def ayb7(self):
        self.bos_ayb()
        self.label_ayb7.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb7.png);")
    def ayb8(self):
        self.bos_ayb()
        self.label_ayb8.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb8.png);")
    def ayb9(self):
        self.bos_ayb()
        self.label_ayb9.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb9.png);")
    def ayb10(self):
        self.bos_ayb()
        self.label_ayb10.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb10.png);")
    def ayb11(self):
        self.bos_ayb()
        self.label_ayb11.setStyleSheet("image: url(C:/Users/pc/PycharmProjects/DressUpGame/img/ayb/ayb11.png);")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
